### ISSUE TITLE
Sphinx build on readthedocs fails

### ISSUE THREAD

**Issue by PythonicNinja** [limebrains/pyotodom#6]
`python /home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`
```
Running Sphinx v1.5.3
making output directory...
WARNING: the config value 'copyright' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
WARNING: the config value 'author' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 248, in build_update
    to_build = list(to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/html.py", line 179, in get_outdated_docs
    self.config_hash = get_stable_hash(cfgdict)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/html.py", line 64, in get_stable_hash
    return get_stable_hash(list(obj.items()))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/html.py", line 66, in get_stable_hash
    obj = sorted(get_stable_hash(o) for o in obj)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/html.py", line 66, in <genexpr>
    obj = sorted(get_stable_hash(o) for o in obj)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/html.py", line 66, in get_stable_hash
    obj = sorted(get_stable_hash(o) for o in obj)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/html.py", line 66, in <genexpr>
    obj = sorted(get_stable_hash(o) for o in obj)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyotodom/envs/latest/lib/python2.7/site-packages/sphinx/builders/html.py", line 67, in get_stable_hash
    return md5(text_type(obj).encode('utf8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 14: ordinal not in range(128)

Encoding error:
'ascii' codec can't decode byte 0xc5 in position 14: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-zDvWMq.log, if you want to report the issue to the developers.
```

**Comment by PythonicNinja** [comment]
Fixed after updating the settings in readthedocs. Changed interpreter to python3.5 in admin settings.
